[features]
seeds = false
skip-lint = false
[programs.localnet]
crowdfunding = "7gBnxsoGc1rgpqhCM6KF1t7ThdqcBj3Jen5nxoAbE5K5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
